// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAverageRSSI():Promise<Array<main.DeviceRSSI>>;

export function InitializeBLE():Promise<void>;

export function IsScanning():Promise<boolean>;

export function StartScan():Promise<void>;

export function StopScan():Promise<void>;
