// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAverageRSSI() {
  return window['go']['main']['App']['GetAverageRSSI']();
}

export function InitializeBLE() {
  return window['go']['main']['App']['InitializeBLE']();
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
